service: zip-s3-files

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-south-1
  iam:
    role: arn:aws:iam::302087542857:role/zip-files-s3-lambda-role

functions:
  zipFilesFromS3:
    handler: src/index.handler
    events:
      - http:
          path: /zip-s3-files
          method: post
          cors: true
